[wokwi]
version = 1
gdbServerPort = 3333
#elf = "target/riscv32imc-unknown-none-elf/debug/esp32_memory_limit"
#firmware = "target/riscv32imc-unknown-none-elf/debug/esp32_memory_limit"


# elf = "target/riscv32imac-unknown-none-elf/debug/examples/01-alloc"
# firmware = "target/riscv32imac-unknown-none-elf/debug/examples/01-alloc"

elf = "target/riscv32imac-unknown-none-elf/debug/examples/02-check-before-alloc"
firmware = "target/riscv32imac-unknown-none-elf/debug/examples/02-check-before-alloc"